name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install EasyQL
        run: pip install -e .

      - name: Run Tests
        run: python -B -m pytest
